// Subjects of the Science Test Builder under their Regents course names. GENERATED by tools/build_question_data.py
// (deploy_site.py runs it): 'updated' is the month of the newest exam in each bank. ready: false greys a card out.
window.SUBJECTS = [
  { id: 'chemistry', name: 'Physical Science: Chemistry', ready: true, updated: 'August 2026' },
  { id: 'physics', name: 'Physical Science: Physics', ready: true, updated: 'June 2026' },
  { id: 'earth', name: 'Earth and Space Sciences', ready: true, updated: 'August 2026' },
  { id: 'biology', name: 'Life Science: Biology', ready: true, updated: 'August 2026' },
];
